Found 60 hdf5 files


Data from: ['/home/robot/Dataset_and_Checkpoint/dataset/stapler_simple']
- Train on [59] episodes
- Test on [1] episodes


Found 60 hdf5 files
Norm stats from: ['/home/robot/Dataset_and_Checkpoint/dataset/stapler_simple']
Initializing transformations
Initializing transformations
Augment images: False, train_num_workers: 2, val_num_workers: 2
/home/ubuntu20/miniforge3/envs/sonicaloha/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/ubuntu20/miniforge3/envs/sonicaloha/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Checkpoint path: /home/ubuntu20/panns_data/Cnn14_mAP=0.431.pth
GPU number: 1
Use VQ: False, None, None
******************************************************************************************************************************************************
number of parameters: 244.73M
KL Weight 10
  0%|                                                                                                                                                       | 45/100001 [00:18<4:42:45,  5.89it/s]Exception ignored in: <generator object tqdm.__iter__ at 0x7f2e224eee40>
Validating
Validation loss: 74.99393
Traceback (most recent call last):
  File "/home/ubuntu20/.local/lib/python3.8/site-packages/tqdm/std.py", line 1182, in __iter__
    yield obj
  File "/home/ubuntu20/miniforge3/envs/sonicaloha/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 40616) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
  0%|                                                                                                                                                      | 45/100001 [00:18<11:41:44,  2.37it/s]
Traceback (most recent call last):
  File "imitate_episodes_multi_gpu.py", line 937, in <module>
    main(vars(parser.parse_args()))
  File "imitate_episodes_multi_gpu.py", line 198, in main
    best_ckpt_info = train_bc(train_dataloader, val_dataloader, config, policy)
  File "imitate_episodes_multi_gpu.py", line 866, in train_bc
    loss.backward()
  File "/home/ubuntu20/miniforge3/envs/sonicaloha/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/ubuntu20/miniforge3/envs/sonicaloha/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
Traceback (most recent call last):
  File "imitate_episodes_multi_gpu.py", line 937, in <module>
    main(vars(parser.parse_args()))
  File "imitate_episodes_multi_gpu.py", line 198, in main
    best_ckpt_info = train_bc(train_dataloader, val_dataloader, config, policy)
  File "imitate_episodes_multi_gpu.py", line 866, in train_bc
    loss.backward()
  File "/home/ubuntu20/miniforge3/envs/sonicaloha/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/ubuntu20/miniforge3/envs/sonicaloha/lib/python3.8/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
KeyboardInterrupt
